management:
  endpoint:
    health:
      show-details: always
spring:
  couchbase:
    env:
      ssl:
        enabled: false
    connection-string: "couchbase://localhost"
    username: userorders
    password: passwordorders
  data:
    couchbase:
      auto-index: true
      bucket-name: orders
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer

event:
  package: com.jinternals.demo.domain.events

debug: false
